app_admin_photographer:
    type: sylius.resource
    prefix: /admin
    resource: |
        alias: app.photographer
        section: admin
        templates: '@SyliusAdmin\\Crud'
        grid: app_photographer
        only: ['index', 'create', 'update', 'delete']

app_admin_event:
    type: sylius.resource
    prefix: /admin
    resource: |
        alias: app.event
        section: admin
        templates: '@SyliusAdmin\\Crud'
        only: ['index', 'create', 'update', 'delete']
        grid: app_event

app_admin_product:
    resource: |
        alias: sylius.product
        section: admin
        templates: '@SyliusAdmin\\Crud'
        only: ['index', 'show', 'update', 'delete']
        grid: app_product
    type: sylius.resource
    prefix: /admin
