sylius_resource:
    resources:
        app.photographer:
            classes:
                model: Sylius\Plugin\PhotoPlugin\Entity\Photographer
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form: Sylius\Plugin\PhotoPlugin\Form\Type\PhotographerType
        app.event:
            classes:
                model: Sylius\Plugin\PhotoPlugin\Entity\Event
                controller: Sylius\Plugin\PhotoPlugin\Controller\EventController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                factory: Sylius\Component\Resource\Factory\Factory
                form: Sylius\Plugin\PhotoPlugin\Form\Type\EventType

sylius_product:
    resources:
        product:
            classes:
                model: Sylius\Plugin\PhotoPlugin\Entity\Product
        product_variant:
            classes:
                model: Sylius\Plugin\PhotoPlugin\Entity\ProductVariant
        
