# src/Plugin/Resources/config/routes.yaml
photographer_login:
    path: /photographer/login
    controller: Sylius\Plugin\PhotoPlugin\Controller\SecurityController::login

photographer_login_check:
    path: /photographer/login_check

photographer_logout:
    path: /photographer/logout

photographer_dashboard:
    path: /admin/photographer/dashboard
    controller: Sylius\Plugin\PhotoPlugin\Controller\PhotographerDashboardController::index

photographer_create:
    path: /admin/photographer/create
    controller: Sylius\Plugin\PhotoPlugin\Controller\PhotographerController::create
    methods: [GET, POST]

photographer_upload:
    path: /admin/photographer/upload
    controller: Sylius\Plugin\PhotoPlugin\Controller\PhotoController::upload

event_photos:
    path: /evenement/{slug}
    controller: Sylius\Plugin\PhotoPlugin\Controller\shop\EventShopController::show
    methods: [GET]

event_list:
    path: /evenements
    controller: Sylius\Plugin\PhotoPlugin\Controller\shop\EventShopController::list
    methods: [GET]
