Sylius\Plugin\PhotoPlugin\Entity\Product\Product:
    type: entity
    table: sylius_product
    fields:
        imageName:
            type: string
            nullable: true
        digitalFilePath:
            type: string
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
